const home=document.querySelector('#home-page');
const casePage=document.querySelector('#case-page');
const content=document.querySelector('#case-content');
const viewer=document.querySelector('#image-viewer');
const viewerImg=document.querySelector('#viewer-image');
const viewerStage=document.querySelector('#viewer-stage');
const track=(event,params={})=>window.portfolioTrack?.(event,params);
let currentCase=null,homeScroll=0,observer=null,viewed=new Set(),galleryItems=[],galleryIndex=0,galleryOpener=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const picture=(name,caption,extra='')=>{const d=ASSET_SIZES[name]||[1800,1200];return `<img src="assets/${name}.webp" alt="${esc(caption)}" width="${d[0]}" height="${d[1]}" loading="lazy" ${extra}>`;};
function figure(item,group){const [name,caption,wide]=item;return `<figure class="${wide==='wide'?'wide':''}"><button class="image-button" data-image="${name}" data-gallery="${group}" data-caption="${esc(caption)}" aria-label="Увеличить: ${esc(caption)}">${picture(name,caption)}<span class="zoom-hint" aria-hidden="true">Увеличить +</span></button><figcaption>${esc(caption)}</figcaption></figure>`;}
const gallery=(items,id,layout='')=>`<div class="gallery ${layout}">${items.map(item=>figure(item,id)).join('')}</div>`;
const heading=(id,num,title,text)=>`<div class="case-section-heading"><span class="section-num" aria-hidden="true">${num}</span><div><h2 data-view="${id}">${title}</h2>${text?`<p>${text}</p>`:''}</div></div>`;
const section=(id,num,title,text,inside='',cls='')=>`<section class="case-section ${cls}" id="${id}">${heading(id,num,title,text)}${inside}</section>`;
const siteLink=(url,title,project)=>`<a class="project-site-link" href="${url}" data-external="${project}" target="_blank" rel="noopener noreferrer"><strong>${title}</strong><span>Действующий сайт · открыть</span></a>`;
function khlBody(data){
 const brand=section('brand-source','—','Что взято из брендбука','Заказчик предоставил логотип, палитру, паттерны, василёк и букву M. Ниже — страницы его брендбука, которые я использовала в работе над одеждой.',gallery([['guide-4','Логотипы / брендбук заказчика'],['guide-8','Палитра / брендбук заказчика'],['guide-14','Василёк и M / брендбук заказчика'],['guide-21','Плашки для графики рукавов / брендбук заказчика']],'brand-source','brand-elements'));
 const overview=section('collection','06','Вся коллекция','Нажмите на модель, чтобы посмотреть эскиз и мокап.',`<div class="collection-overview">${data.models.map(m=>`<button class="model-link" data-jump="${m.id}">${picture(m.thumbnail||m.visual,m.title)}<span>${m.number} / ${m.title}</span></button>`).join('')}</div>`);
 return brand+overview+data.models.map(m=>section(m.id,m.number,`${m.title}<em>${m.concept}</em>`,m.text,`<p class="eyebrow">${m.detail}</p>`+gallery([[m.sketch,m.revision?'Первоначальный дизайн / технический эскиз':'Эскиз / техническая презентация'],[m.visual,m.revision?'Обновлённый дизайн / мокап':m.ai?'AI-визуализация / общий вид изделия':'Визуализация / внешний вид изделия']],m.id)+(m.revision?`<p class="note">${esc(m.revision)}</p>`:'')+ (m.ai?'<p class="note">AI-визуализация. Детали графики и надписи могут отличаться от эскиза.</p>':''),'model-section')).join('')+section('colors','04','Командные цвета','Для каждой из шести моделей подготовила четыре цветовых варианта — по одному для каждой команды. Здесь показаны листы из презентации. Свитшот №1 на них ещё в первоначальном дизайне.',gallery([['khl-colors-2','Лонгслив / четыре командных цвета'],['khl-colors-6','Свитшот №1 / четыре цвета первоначального дизайна'],['khl-colors-8','Свитшот №2 / четыре командных цвета'],['khl-colors-10','Худи / четыре командных цвета'],['khl-colors-12','Футболка Classic / четыре командных цвета'],['khl-colors-16','Футболка Oversize / четыре командных цвета']],'colors'));
}
function identityBody(){return section('voz','01','Центр «Возрождение»','Фирменный стиль для центра образовательных, культурных и общественных проектов.',siteLink('https://vozrozh.ru/about','Центр «Возрождение»','vozrozhdenie')+`<div class="brand-display">${picture('voz-mark','Логотип центра Возрождение')}</div><div class="brand-story"><div><h3>Логотип</h3><p>В знаке соединила парящего орла и горный пейзаж. Подготовила отдельную эмблему и версию с названием центра.</p></div><div><h3>Паттерны и брендбук</h3><p>Разработала паттерны для сайта, упаковки и пресс-стены. В брендбуке собрала цвета, шрифты и правила использования логотипа.</p></div></div>`+gallery([['voz-webpattern','Геометрический веб-паттерн'],['voz-packaging','Применение упаковочного паттерна'],['voz-6','Палитра и цветовые спецификации'],['voz-presswall','Применение на пресс-стене']],'voz'))+section('chudo','02','Фонд «Чудотворцы»','Логотип, иллюстрации и оформление материалов для благотворительного фонда.',siteLink('https://bfchudo.ru/','Благотворительный фонд «Чудотворцы»','chudotvortsy')+`<div class="brand-display">${picture('chudo-mark','Логотип благотворительного фонда Чудотворцы')}</div><div class="brand-story"><div><h3>Логотип фонда</h3><p>В логотипе изобразила руку и ленту в форме сердца. Из лент также собрала паттерн для упаковки и других материалов фонда.</p></div><div><h3>Иллюстрации</h3><p>Нарисовала серию линейных иллюстраций с семьями, волонтёрами и людьми, которым помогает фонд.</p></div></div>`+gallery([['chudo-family','Авторская иллюстрация / семья'],['chudo-ribbons-clean','Система декоративных лент'],['chudo-illustrations-clean','Серия авторских иллюстраций','wide'],['chudo-packaging-clean','Применение на упаковке'],['chudo-6','Фирменная палитра']],'chudo'));
}
function renderCase(key){const d=CASES[key];return `<div class="case-hero"><p class="eyebrow">${d.number} / ИЗБРАННЫЙ ПРОЕКТ</p><h1 class="case-title" tabindex="-1">${d.title}<em>${d.subtitle}</em></h1><div class="case-intro"><p>${d.intro}</p><div class="case-role"><b>МОЯ РОЛЬ</b>${d.role}</div></div><div class="facts">${d.facts.map(([v,l])=>`<div><strong>${v}</strong><span>${l}</span></div>`).join('')}</div></div><nav class="case-nav" aria-label="Разделы кейса">${d.nav.map(([id,label])=>`<button data-jump="${id}" aria-current="false">${label}</button>`).join('')}</nav>${key==='khl'?`<p class="note">${d.note}</p>`:''}${key==='identity'?identityBody():key==='khl'?khlBody(d):d.sections.map(s=>section(s.id,s.number,s.title,s.text,gallery(s.images,s.id,s.layout||''))).join('')}${key==='forward'?`<p class="note">${d.note}</p>`:''}<div class="case-end" data-complete><div><p class="eyebrow">ОБСУДИМ РАБОТУ?</p><a href="https://t.me/klixxe" data-contact="telegram" target="_blank" rel="noopener noreferrer">Написать в Telegram</a></div><a href="#case/${d.next}" data-case-link="${d.next}">Далее: ${CASES[d.next].title}</a></div>`;}
function typography(root){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){if(!['SCRIPT','STYLE'].includes(n.parentElement.tagName))n.textContent=n.textContent.replace(/(^|[\s\u00a0])([ИиАаВвКкСсУуОо]|[Нн]а|[Пп]о|[Оо]т|[Нн]е|[Ии]з) /g,'$1$2\u00a0');}}
function observeCase(){observer?.disconnect();viewed=new Set();observer=new IntersectionObserver(entries=>{for(const e of entries){if(!e.isIntersecting)continue;const id=e.target.dataset.view||'complete';if(!viewed.has(id)){viewed.add(id);track(id==='complete'?'case_complete':'section_view',{case_id:currentCase,...(id==='complete'?{}:{section_id:id})});}if(id!=='complete'){content.querySelectorAll('.case-nav button').forEach(b=>b.setAttribute('aria-current',String(b.dataset.jump===id)));}}},{rootMargin:'-135px 0px -15% 0px',threshold:.15});content.querySelectorAll('[data-view],[data-complete]').forEach(el=>observer.observe(el));}
function route(){const key=location.hash.startsWith('#case/')?location.hash.slice(6):null;
 if(key&&CASES[key]){if(!currentCase)homeScroll=window.scrollY;currentCase=key;home.hidden=true;casePage.hidden=false;content.innerHTML=renderCase(key);typography(content);document.title=`${CASES[key].title} — Klixxe`;window.scrollTo({top:0,behavior:'instant'});content.querySelector('.case-title').focus({preventScroll:true});observeCase();track('case_open',{case_id:key});}
 else{const previousCase=currentCase;const wasCase=!!currentCase;currentCase=null;observer?.disconnect();casePage.hidden=true;home.hidden=false;document.title='Klixxe — Екатерина Титова · Дизайнер';if(wasCase){requestAnimationFrame(()=>{if(location.hash==='#work'){window.scrollTo({top:homeScroll,behavior:'instant'});home.querySelector(`[data-case-link="${previousCase}"]`)?.focus({preventScroll:true});}else{const el=document.getElementById(location.hash.slice(1));if(el)el.scrollIntoView();else window.scrollTo({top:0,behavior:'instant'});}});}}
 window.portfolioPageView?.(currentCase);updateProgress();}
function updateProgress(){if(!currentCase)return;const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.reading-progress').style.setProperty('--progress',`${max>0?Math.min(100,scrollY/max*100):0}%`);}
function updateImage(){const item=galleryItems[galleryIndex];viewerImg.src=`assets/${item.name}.webp`;viewerImg.alt=item.caption;document.querySelector('#viewer-caption').textContent=item.caption;document.querySelector('#viewer-count').textContent=`${galleryIndex+1} / ${galleryItems.length}`;document.querySelector('#previous-image').disabled=galleryIndex===0;document.querySelector('#next-image').disabled=galleryIndex===galleryItems.length-1;viewerStage.classList.remove('zoomed');document.querySelector('#zoom-image').setAttribute('aria-pressed','false');document.querySelector('#zoom-image').textContent='Увеличить';viewerStage.scrollTop=0;viewerStage.scrollLeft=0;}
function nextImage(delta){const next=galleryIndex+delta;if(next<0||next>=galleryItems.length)return;galleryIndex=next;updateImage();}
document.addEventListener('click',async e=>{const target=e.target.closest('a,button');if(!target)return;
 if(target.dataset.jump){document.getElementById(target.dataset.jump)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
 if(target.dataset.image){galleryOpener=target;galleryItems=Array.from(content.querySelectorAll(`[data-gallery="${target.dataset.gallery}"]`)).map(el=>({name:el.dataset.image,caption:el.dataset.caption}));galleryIndex=galleryItems.findIndex(it=>it.name===target.dataset.image);updateImage();viewer.showModal();document.body.classList.add('viewer-open');track('gallery_open',{case_id:currentCase,asset:target.dataset.image});}
 if(target.dataset.contact)track('contact_click',{channel:target.dataset.contact,case_id:currentCase||'home'});
 if(target.dataset.external)track('external_site',{project:target.dataset.external});
 if(target.hasAttribute('data-copy-email')){const status=document.querySelector('.copy-status');try{await navigator.clipboard.writeText('anutoca2005@mail.ru');status.textContent='Почта скопирована';track('email_copy');}catch{status.textContent='Почта: anutoca2005@mail.ru';}setTimeout(()=>{status.textContent='';},6000);}
});
document.querySelector('#close-viewer').addEventListener('click',()=>viewer.close());
document.querySelector('#previous-image').addEventListener('click',()=>nextImage(-1));document.querySelector('#next-image').addEventListener('click',()=>nextImage(1));
document.querySelector('#zoom-image').addEventListener('click',e=>{const z=viewerStage.classList.toggle('zoomed');e.currentTarget.setAttribute('aria-pressed',String(z));e.currentTarget.textContent=z?'Вписать':'Увеличить';if(z)track('gallery_zoom',{case_id:currentCase,asset:galleryItems[galleryIndex].name});});
viewer.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();nextImage(1)}if(e.key==='ArrowLeft'){e.preventDefault();nextImage(-1)}});
viewer.addEventListener('close',()=>{document.body.classList.remove('viewer-open');galleryOpener?.focus({preventScroll:true});});
let touchX=0,touchY=0;viewerStage.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX;touchY=e.changedTouches[0].clientY;},{passive:true});viewerStage.addEventListener('touchend',e=>{if(viewerStage.classList.contains('zoomed'))return;const dx=e.changedTouches[0].clientX-touchX,dy=e.changedTouches[0].clientY-touchY;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)nextImage(dx<0?1:-1);},{passive:true});
window.addEventListener('hashchange',()=>{if(viewer.open)viewer.close();route();});window.addEventListener('scroll',updateProgress,{passive:true});
typography(home);route();
const studioExamples={
 print:{image:'aurora-preview',alt:'Принт Северное сияние на спортивном комплекте',text:'Рисую принт и раскладываю его по лекалам, учитывая швы и стыки рисунка.',caption:'FORWARD / Северное сияние · AI-визуализация',href:'#case/forward',link:'Смотреть FORWARD'},
 cut:{image:'hoodie-product-final',alt:'Худи KHL All Star спереди и сзади',text:'Подбираю фасон и отделку, размещаю графику на изделии. Для согласования собираю эскизы и мокапы.',caption:'KHL ALL STAR / Худи · AI-визуализация',href:'#case/khl',link:'Смотреть коллекцию'},
 brand:{image:'chudo-mark',alt:'Логотип благотворительного фонда Чудотворцы',text:'Создаю логотипы, паттерны и иллюстрации. Собираю в брендбук правила и примеры их использования.',caption:'ЧУДОТВОРЦЫ / Авторский логотип',href:'#case/identity',link:'Смотреть айдентику'}
};
function selectStudio(button){const key=button.dataset.studio,item=studioExamples[key];document.querySelectorAll('[data-studio]').forEach(b=>{b.setAttribute('aria-selected',String(b===button));b.tabIndex=b===button?0:-1;});const im=document.querySelector('#studio-image');im.src=`assets/${item.image}.webp`;im.alt=item.alt;im.width=ASSET_SIZES[item.image][0];im.height=ASSET_SIZES[item.image][1];document.querySelector('#studio-text').textContent=item.text;document.querySelector('#studio-caption').textContent=item.caption;document.querySelector('#studio-link').href=item.href;document.querySelector('#studio-link').textContent=item.link;document.querySelector('#studio-panel').setAttribute('aria-labelledby',button.id);track('discipline_view',{discipline:key});}
document.querySelectorAll('[data-studio]').forEach(button=>{button.addEventListener('click',()=>selectStudio(button));button.addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('[data-studio]')];let i=tabs.indexOf(button);if(e.key==='ArrowRight'||e.key==='ArrowDown')i=(i+1)%tabs.length;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')i=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=tabs.length-1;else return;e.preventDefault();selectStudio(tabs[i]);tabs[i].focus();});});
